# -*- coding: utf-8 -*-
"""ECOSNAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNYEq6o4gR7fVAfAOqWmtMOuFZICH0l0

Install Required Packages
"""

# Core imports
import streamlit as st
from PIL import Image
import numpy as np
import base64
from io import BytesIO
from datetime import datetime, timedelta
import random

st.set_page_config(page_title="EcoSnap", layout="wide")


# Stores user data (like CO2 saved, streaks)
db_users = {}

# Stores uploaded image data
db_images = []

# Simulated rewards and CSR employee mappings
db_rewards = {
    "R1": "5% Discount Coupon",
    "R2": "Reusable Water Bottle",
    "R3": "Eco-Friendly Tote Bag"
}
db_csr = {
    "CSR1": ["user1", "user2", "user3"],
    "CSR2": ["user4", "user5"]
}


# Simulated AI classifier for recognizing eco-friendly actions from images
ACTION_LABELS = {
    0: "bicycle",
    1: "public_transport",
    2: "recycling",
    3: "using_reusable_bags",
    4: "planting_tree"
}

def dummy_ai_analyzer(image_bytes):
    # Randomly returns an action (simulating AI output)
    return random.choice(list(ACTION_LABELS.keys()))


# Estimates CO₂ savings based on detected action and optional distance
def estimate_co2(action_idx, parameters):
    co2_map = {
        0: 0.75,  # bicycle per 3 km
        1: 0.5,   # public transport per trip
        2: 0.2,   # recycling
        3: 0.1,   # reusable bags
        4: 2.0    # planting tree
    }
    base = co2_map.get(action_idx, 0)
    distance = parameters.get('distance', 1)
    if action_idx in [0,1]:
        return base * (distance / 3)
    else:
        return base


# Updates daily streaks for users based on current date
def update_user_streak(user_id, current_date):
    user = db_users.get(user_id, {})
    last_action_date = user.get("last_action_date")
    streak = user.get("streak_count",0)

    if last_action_date:
        diff = (current_date - last_action_date).days
        if diff == 1:
            streak += 1
        elif diff > 1:
            streak = 1
    else:
        streak = 1

    user["last_action_date"] = current_date
    user["streak_count"] = streak
    db_users[user_id] = user
    return streak


def update_user_co2(user_id, co2):
    user = db_users.get(user_id, {})
    total = user.get("total_co2_saved", 0) + co2
    daily = co2  # simple version, otherwise track by date
    user["total_co2_saved"] = total
    user["daily_co2_savings"] = daily
    # Save historical actions as list
    history = user.get("historical_activity", [])
    history.append({"date": datetime.now().strftime("%Y-%m-%d"), "co2": co2})
    user["historical_activity"] = history
    # Manage available rewards (example threshold)
    rewards = user.get("available_rewards", [])
    if total >= 10 and "R1" not in rewards:
        rewards.append("R1")
    if total >= 30 and "R2" not in rewards:
        rewards.append("R2")
    if total >= 50 and "R3" not in rewards:
        rewards.append("R3")
    user["available_rewards"] = rewards
    db_users[user_id] = user


def main():
    st.title("EcoSnap App 🌍 – Sustainable Action Tracker")

    menu = ["EcoSnap Camera", "Streak Tracker", "Leaderboard", "Reward Center", "CSR Dashboard", "Personal Dashboard"]
    choice = st.sidebar.selectbox("Select Feature", menu)

    if choice == "EcoSnap Camera":
        st.header("Upload Your Eco-Friendly Action Image")
        uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
        if uploaded_file:
            st.image(uploaded_file, caption='Uploaded Image', use_column_width=True)
            bytes_data = uploaded_file.read()
            img_base64 = base64.b64encode(bytes_data).decode('utf-8')

            user_id = st.text_input("Enter Your User ID")
            distance = 0.0
            if st.checkbox("Does your action involve distance?"):
                distance = st.number_input("Enter distance in km", min_value=0.0, step=0.1)

            if st.button("Analyze and Save"):
                if not user_id:
                    st.error("Please enter User ID.")
                else:
                    action_idx = dummy_ai_analyzer(bytes_data)
                    action_name = ACTION_LABELS[action_idx]
                    co2_saved = estimate_co2(action_idx, {'distance': distance})

                    st.success(f"Detected Action: {action_name}")
                    st.info(f"Estimated CO₂ Saved: {co2_saved:.3f} kg")

                    db_images.append({
                        "user_id": user_id,
                        "image_data": img_base64,
                        "timestamp": datetime.now(),
                        "action": action_name,
                        "co2_saved": co2_saved
                    })

                    update_user_co2(user_id, co2_saved)
                    update_user_streak(user_id, datetime.now().date())

                    st.success("Action Saved Successfully! 💚")

    elif choice == "Streak Tracker":
        st.header("Your Eco-Friendly Action Streak")
        user_id = st.text_input("Enter Your User ID")
        if st.button("Check Streak"):
            streak = db_users.get(user_id, {}).get("streak_count", 0)
            st.info(f"Current Streak: {streak} day(s)")

    elif choice == "Leaderboard":
        st.header("Top EcoSnap Users by CO₂ Saved")
        leaderboard = sorted(((uid, u.get("total_co2_saved", 0)) for uid, u in db_users.items()),
                             key=lambda x: x[1], reverse=True)[:10]
        for i, (uid, co2) in enumerate(leaderboard, start=1):
            st.write(f"{i}. User {uid}: {co2:.2f} kg")

    elif choice == "Reward Center":
        st.header("Redeem Your Rewards")
        user_id = st.text_input("Enter Your User ID")
        user = db_users.get(user_id, {})
        available = user.get("available_rewards", [])
        redeemed = user.get("redeemed_rewards", [])

        st.subheader("Available Rewards")
        if available:
            reward = st.selectbox("Select Reward", available)
            if st.button("Redeem"):
                if reward:
                    available.remove(reward)
                    redeemed.append(reward)
                    user["available_rewards"] = available
                    user["redeemed_rewards"] = redeemed
                    db_users[user_id] = user
                    st.success(f"Reward {reward} redeemed!")
        else:
            st.info("No rewards available yet.")

    elif choice == "CSR Dashboard":
        st.header("CSR Partner Dashboard")
        csr_id = st.text_input("Enter CSR ID")
        if csr_id:
            user_list = db_csr.get(csr_id, [])
            total = sum(db_users.get(uid, {}).get("total_co2_saved", 0) for uid in user_list)
            count = sum(1 for uid in user_list if db_users.get(uid, {}).get("total_co2_saved", 0) > 0)
            st.write(f"Total CO₂ Saved: {total:.2f} kg")
            st.write(f"Participating Employees: {count}")

    elif choice == "Personal Dashboard":
        st.header("Your EcoSnap Dashboard")
        user_id = st.text_input("Enter Your User ID")
        if st.button("Show Dashboard"):
            user = db_users.get(user_id)
            if not user:
                st.error("User not found.")
            else:
                st.write(f"Daily CO₂ Savings: {user.get('daily_co2_savings', 0):.2f} kg")
                st.write(f"Streak: {user.get('streak_count', 0)} day(s)")
                st.write(f"Total CO₂ Saved: {user.get('total_co2_saved', 0):.2f} kg")
                st.subheader("Recent Activity")
                for h in user.get("historical_activity", [])[-10:]:
                    st.write(f"{h['date']}: {h['co2']:.3f} kg")

if __name__ == "__main__":
    main()
